== Inject a service or an argument

Sometimes it is required to inject a service that is not autowired, or a specific parameter without accessing to the whole ParameterBag.

=== In the constructor

To do so, add the `Argument` annotation/attribute on the class with the appropriate values. Here is an example where we inject the `doctrine` service, the default locale and all the tagged command into the constructor:

[source, php]
----
use RichId\AutoconfigureBundle\Annotation as Service;

#[
    Service\Argument('$doctrine', 'doctrine'),
    Service\Argument('$locale', 'kernel.default_locale', type='parameter'),
    Service\Argyment('commands', 'console.command', type='services_by_tag'),
]
class RandomService
{
    public function __construct($doctrine, string $locale, array $commands)
    {
        ...
    }
}
----

=== In a public property

To do so, add the `Property` annotation/attribute on the class with the appropriate values. Here is an example where we inject the `doctrine` service, the default locale and all the tagged commands into the corresponding public properties:

[source, php]
----
use RichId\AutoconfigureBundle\Annotation as Service;

#[
    Service\Property('doctrine', 'doctrine'),
    Service\Property('locale', 'kernel.default_locale', type='parameter'),
    Service\Property('commands', 'console.command', type='services_by_tag'),
]
class RandomService
{
    public $doctrine;
    public string $locale;
    public array $commands;
}
----

=== In a public method

To do so, add the `Method` annotation/attribute on the class with the appropriate values. Here is an example where we inject the 2 values to a method and all the tagged commands to another one.

[source, php]
----
use RichId\AutoconfigureBundle\Annotation as Service;

#[
    Service\Method('setValues', 'doctrine'),
    Service\Method('setValues', 'kernel.default_locale', type='parameter', position=1),
    Service\Method('setCommands', 'console.command', type='services_by_tag'),
]
class RandomService
{
    public function setValues($doctrine, string $locale): void
    {
        // ...
    }

    public function setCommands(array $commands): void
    {
        // ...
    }
}
----
